# SUMAUTO EDA
 - Author   : Jon Ugalde García-Vera
 - Date     : 2026

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

## DATA ACQUISITION

In [ ]:
PATH = '../data/'

df_advertiser       = pd.read_parquet(PATH + 'zrive_dim_advertiser.parquet')
df_monthly_snapshot = pd.read_parquet(PATH + 'zrive_fct_monthly_snapshot_advertiser.parquet')
df_withdrawal       = pd.read_parquet(PATH + 'zrive_advertiser_withdrawals.parquet')

,advertiser_zrive_id,province_id,updated_at,advertiser_province,advertiser_group_id,min_start_contrato_date,max_start_contrato_nuevo_date,contrato_churn_date
0,986,1,2025-05-01 02:46:04,Álava,194.0,2025-01-07,2025-01-07,2025-05-17
1,6811,1,2025-02-05 01:02:08,Álava,NaN,2025-01-24,None,2025-02-04
2,4890,2,2024-08-09 13:38:43,Albacete,133.0,2023-02-24,None,2023-06-03
3,3428,3,2023-11-02 13:51:07,Alicante,NaN,2023-03-17,2023-03-17,2023-11-01
4,547,3,2024-02-05 13:49:02,Alicante,NaN,2023-05-03,None,2023-12-29

In [ ]:
df_advertiser.isna()

,advertiser_zrive_id,province_id,updated_at,advertiser_province,advertiser_group_id,min_start_contrato_date,max_start_contrato_nuevo_date,contrato_churn_date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,True,False
2,False,False,False,False,False,False,True,False
3,False,False,False,False,True,False,False,False
4,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...
7071,False,False,False,False,True,False,False,False
7072,False,False,False,False,True,False,False,False
7073,False,False,False,False,True,False,False,False
7074,False,False,False,False,True,False,False,False
7075,False,False,False,False,True,False,True,False